name: Java CI with Maven and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ElasticServiceEnv
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-west-2'

      - name: Upload JAR to AWS S3
        run: aws s3 cp target/ElasticService-0.0.1-SNAPSHOT.jar s3://elastic-service-app/ElasticService-0.0.1-SNAPSHOT.jar

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ github.workspace }}/terraform/deployment

      - name: Terraform Plan
        run: terraform plan -out=full.plan
        working-directory: ${{ github.workspace }}/terraform/deployment

      - name: Terraform Apply
        run: terraform apply "full.plan"
        working-directory: ${{ github.workspace }}/terraform/deployment
